#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoIbFoam"

runApplication blockMesh

runApplication refineCylinderMesh

#runApplication refineImmersedBoundaryMesh

#rm log.refineImmersedBoundaryMesh
#runApplication refineImmersedBoundaryMesh

runApplication $application
