#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="makeTriSurfaceMesh"

runApplication blockMesh

runApplication $application

cp immersedBoundary.* ../flowOverCylinder/constant/triSurface