#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="makeTriSurfaceMesh"

gzip -d thickPlate.msh.gz

runApplication fluentMeshToFoam thickPlate.msh

transformPoints -rotateAlongVector "(0 0 1) 5"

gzip thickPlate.msh

runApplication $application

cp immersedBoundary.* ../flowOverThickPlate/constant/triSurface