#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoIbFoam"

rm -rf 0
mkdir 0
mkdir constant/polyMesh
cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh
cp -f boundary_1 constant/polyMesh/boundary
runApplication refineImmersedBoundaryMesh
rm -rf constant/polyMesh
mv 0/polyMesh constant/polyMesh

rm -rf 0
cp -r save 0

runApplication potentialIbFoam
runApplication $application
