#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="makeTriSurfaceMesh"

gzip -d sphere_D1.0_dL0.01.msh.gz

runApplication fluentMeshToFoam sphere_D1.0_dL0.01.msh

gzip sphere_D1.0_dL0.01.msh

runApplication $application

cp immersedBoundary.* ../flowOverSphere/constant/triSurface