#!/bin/sh

( cd cavity ; foamCleanTutorials )

( cd flowOverCylinder ; foamCleanTutorials )

( cd pitzDailyLaminar ; ./Allclean )

( cd damBreakWithCylinder ; ./Allclean )


( cd flowOverSphere ; ./Allclean )
