#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="makeTriSurfaceMesh"

gzip -d silencer.msh.gz

runApplication fluentMeshToFoam silencer.msh

gzip silencer.msh

runApplication $application

cp immersedBoundary.* ../silencer/constant/triSurface