#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application name
application="icoIbFoam"

rm -rf 0
cp -r save 0
mkdir constant/polyMesh
cp -f blockMeshDict constant/polyMesh/blockMeshDict
runApplication blockMesh
cp -f boundary constant/polyMesh/boundary

runApplication potentialIbFoam
runApplication $application
