#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
(cd refineCylinderMesh; cleanApplication)

\rm -rf 0
cp -r save 0

rm -rf constant/polyMesh/
mkdir constant/polyMesh